name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm i -g yarn && yarn && npx playwright install --with-deps

      - name: Run smoke tests
        run: yarn test:smoke

      - name: Run unit tests
        run: yarn test:unit

      - name: Build task
        run: yarn build

      - name: Run E2E tests
        run: yarn test:e2e

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: ${{ secrets.LOCAL_SOURCE }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_BEFORE: ls
          SCRIPT_BEFORE_REQUIRED: true
          SCRIPT_AFTER: ${{ secrets.SCRIPT_AFTER }}
          SCRIPT_AFTER_REQUIRED: true
          EXCLUDE: "/dist/, /node_modules/"
